connector.name=delta_lake
hive.metastore.uri=thrift://hive-metastore:9083
hive.s3.endpoint=http://localstack:4566
hive.s3.path-style-access=true
hive.s3.aws-access-key=test
hive.s3.aws-secret-key=test
delta.register-table-procedure.enabled=true
delta.enable-non-concurrent-writes=true
